-- User Creation
CREATE USER retail_store
IDENTIFIED BY pass123;

GRANT CONNECT, RESOURCE TO retail_store;

-- Customer Table
CREATE TABLE Customers (
customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
first_name VARCHAR2(50),
last_name VARCHAR2(50),
email VARCHAR2(100) UNIQUE,
phone VARCHAR(15),
city VARCHAR2(50),
registration_date DATE DEFAULT SYSDATE
);

-- Product Table
CREATE TABLE Products (
product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
product_name VARCHAR2(100) NOT NULL,
category VARCHAR2(50),
price NUMBER(10,2) CHECK (price>0),
stock_quantity NUMBER(5) CHECK (stock_quantity >= 0)
);

-- Orders Table
CREATE TABLE Orders (
order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
customer_id NUMBER REFERENCES Customers(customer_id),
order_date DATE DEFAULT SYSDATE,
total_amount NUMBER(10,2)
);

-- OrderDetails Table (Many-to-Many Orders & Products)
CREATE TABLE OrderDetails (
order_id NUMBER REFERENCES Orders(order_id),
product_id NUMBER REFERENCES Products(product_id),
quantity NUMBER(5) CHECK (quantity > 0),
PRIMARY KEY (order_id, product_id)
);

-- Payment Table
CREATE TABLE Payments (
payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
order_id NUMBER REFERENCES Orders(order_id),
payment_date DATE DEFAULT SYSDATE,
payment_method VARCHAR2(20),
amount NUMBER(10,2)
);

-- Add a column to an existing table
ALTER TABLE Customers
ADD date_of_birth DATE;

SELECT * FROM Customers;

-- Rename an existing column
ALTER TABLE Customers
RENAME COLUMN date_of_birth TO dob;

-- Drop a column if not needed
ALTER TABLE Customers
DROP COLUMN dob;

-- Rename a table 
ALTER TABLE Customers
RENAME TO Client_Details;

SELECT * FROM Client_Details;

ALTER TABLE Client_Details
RENAME TO Customers;

SELECT * FROM Customers;